# This is a basic workflow to help you get started with Actions

name: first github action 
on: workflow_dispatch
jobs: 
  first-job: 
     runs-on: ubuntu-latest 
     steps: 
       - name: say hellow 
         run: echo "welcome to git hub actions" 

         
